redis:
    image: redis
    ports:
        - 6379:6379
    volumes:
        - ./data/redis:/data
  
mysql:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - 3306:3306
    volumes:
        - ./data/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: example